version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "quarterly"
    labels:
      - "dependencies"
    groups:
      gomod-all:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    labels:
      - "dependencies"
    groups:
      actions-all:
        patterns:
          - "*"
