# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: grapple

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/dippi/grapple/cmd.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - completions/*
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

snapshot:
  version_template: 0.0.0-SNAPSHOT-{{ .ShortCommit }}

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  disable: true

homebrew_casks:
  - name: grapple
    binary: grapple
    homepage: https://github.com/dippi/grapple
    description: Fetch logs from Google Cloud Logging
    license: MIT
    repository:
      owner: dippi
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    completions:
      bash: completions/grapple.bash
      zsh: completions/grapple.zsh
      fish: completions/grapple.fish
